config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  devise_for :organizations
  resources :users
  resources :messages
  resources :message_templates
  resources :sms_templates
  resources :short_codes
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

    def index
    end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="m-auto grid grid-cols-2 gap-4 items-center justify-center">
    <div class="p-4">
      <div class="flex items-center justify-center">
        <%= image_tag('logo.gif', alt: 'Yamdoot Image', class: 'max-w-full h-auto') %>
      </div>
      <div class="text-center mt-4">
        <b class="text-xl">Your All-in-One Communication Solution</b>
        <p class="mt-2 text-gray-700">
          YamDuut is designed to streamline and simplify your organization's communication efforts. Our platform allows you to manage your members and effortlessly send SMS, WhatsApp messages, and emails from a single, user-friendly interface.
        </p>
      </div>
    </div>
    <div class="p-4">
      <%= turbo_frame_tag "forms_portation" do %>
      <div class="text-left mb-4">
        <b class="text-3xl block">Why Choose YamDuut?</b>
        <b class="block mt-4 text-2xl">Unified Communication:</b>
        <p class="text-gray-700 text-lg">Manage all your communication channels in one place. No need to switch between different apps or services.</p>
        <b class="block mt-4 text-2xl">Effortless Member Management:</b>
        <p class="text-gray-700 text-lg">Easily add, update, and organize your members' information.</p>
        <b class="block mt-4 text-2xl">Multi-Channel Messaging:</b>
        <p class="text-gray-700 text-lg">Send messages via SMS, WhatsApp, or email with just a few clicks.</p>
        <b class="block mt-4 text-2xl">Analytics and Reports:</b>
        <p class="text-gray-700 text-lg">Track the effectiveness of your messages and get insights into your communication strategies.</p>
      </div>      
        <div class="mt-5 flex items-center justify-start">
            <% if controller_name != 'registrations' %>
              <%= link_to "Create Organization", new_registration_path(:organization), class: 'bg-white text-green-500 hover:text-white hover:bg-green-500 font-bold py-2 px-4 rounded', data: { turbo_frame: 'forms_portation' } %>
            <% end unless organization_signed_in? %>
            <% if controller_name != 'sessions' %>
              <%= link_to "Sign up", new_session_path(:organization), class: "ml-8 bg-white text-green-500 hover:text-white hover:bg-green-500 font-bold py-2 px-4 rounded", data: { turbo_frame: 'forms_portation' } %><br />
            <% end unless organization_signed_in? %>
            <% if organization_signed_in? %>
              <%= link_to "Manage Users", users_path, class: "ml-8 bg-white text-green-500 hover:text-white hover:bg-green-500 font-bold py-2 px-4 rounded", data: { turbo: false } %><br />
              <%= link_to "Send messages", messages_path, class: "ml-8 bg-white text-green-500 hover:text-white hover:bg-green-500 font-bold py-2 px-4 rounded", data: { turbo: false } %><br />
              <%= link_to "Create SMS Template", sms_templates_path, class: "ml-8 bg-white text-green-500 hover:text-white hover:bg-green-500 font-bold py-2 px-4 rounded", data: { turbo: false } %><br />
            <% end %>
        </div>          
      <% end %>
    </div>
  </div>
  