config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  devise_for :organizations
  resources :users
  resources :messages
  resources :message_templates
  resources :sms_templates
  resources :short_codes
end

app/models/message_template.rb
class MessageTemplate < ApplicationRecord
    # Associations
    belongs_to :organization
  
    # Validations
    validates :title, presence: true, length: { minimum: 5, maximum: 100 }
    validates :content, presence: true
    validates :organization_id, presence: true
  end
  

app/controllers/message_templates_controller.rb
class MessageTemplatesController < ApplicationController
    before_action :check_organization_login
    before_action :set_template, only: [:edit, :update, :destroy]
  
    def index
      @templates = current_organization.message_templates rescue []
    end
  
    def new
      @template = current_organization.message_templates.build
    end
  
    def edit
    end
  
    def create
      @template = current_organization.message_templates.build(template_params)
      @template.save
      respond_to do |format|
        format.turbo_stream 
      end
    end
  
    def update
      respond_to do |format|
        if @template.update(template_params)
          format.turbo_stream
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('form_errors', partial: 'message_templates/form_errors', locals: { template: @template })
          end
        end
      end
    end
  
    def destroy
      @template.destroy
      respond_to do |format|
        format.turbo_stream 
      end
    end
  
    private

    def check_organization_login
      unless organization_signed_in?
        redirect_to root_path, alert: 'Please log in to continue.'
      end
    end
  
    def set_template
      @template = current_organization.message_templates.find(params[:id])
    end
  
    def template_params
      params.require(:message_template).permit(:title, :content, :organizations_id)
    end
end

app/helpers/message_templates_helper.rb
module MessageTemplatesHelper
end

app/views/message_templates/_form.html.erb
  <div class="border border-green-500  bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <%= form_with(model: template, local: false) do |form| %>
    <% if template.errors.any? %>
      <div id="error_explanation" class="mb-4">
        <h2 class="text-red-500"><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>
        <ul class="list-disc list-inside text-red-500">
          <% template.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="mb-4">
      <%= form.label :content, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-24" %>
    </div>
    <div>
      <%= form.submit "Save", class: "bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to "Cancel", "#", class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline",  onclick: "this.closest('[data-turbo-frame]').innerHTML = '';" %>
    </div>
  <% end %>
  </div>

app/views/message_templates/_form_errors.html.erb
<% if template.errors.any? %>
<div data-controller="alert" data-alert-target="alert" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert" id="form_errors">
  <strong class="font-bold">Error!</strong>
  <span class="block sm:inline"><%= template.errors.full_messages.first rescue "SomeThing Went Wrong.!" %></span>
  <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
    <svg data-action="click->alert#close" class="fill-current h-6 w-6 text-red-500 cursor-pointer" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
      <title>Close</title>
      <path d="M14.348 5.652a1 1 0 10-1.414-1.414L10 7.586 7.066 4.652A1 1 0 105.652 6.066L8.586 9l-2.934 2.934a1 1 0 101.414 1.414L10 10.414l2.934 2.934a1 1 0 001.414-1.414L11.414 9l2.934-2.934z"/>
    </svg>
  </span>
</div>
<% end %>

app/views/message_templates/_no_records.html.erb
<div id="no-records" class="text-gray-500 text-center">
  No records found.
</div>

app/views/message_templates/_template.html.erb
<%= turbo_frame_tag dom_id(template) do %>
  <div class="p-4 border rounded flex justify-between items-center mb-4">
    <div>
      <h3 class="font-bold"><%= template.title %></h3>
      <p><%= template.content %></p>
    </div>
    <div class="flex space-x-4">
      <%= link_to edit_message_template_path(template), class: "text-blue-500 hover:text-blue-700 px-4", data: { turbo_frame: dom_id(template) } do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to message_template_path(template), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-red-500 hover:text-red-700 px-4" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/message_templates/create.turbo_stream.erb
<% if @template.save %>
    <%= turbo_stream.update "create-template", "" %>
    <% if MessageTemplate.count == 1 %>
    <%= turbo_stream.update "message_templates", partial: "template", locals: { template: @template } %>
    <% else %>
    <%= turbo_stream.append "message_templates", partial: "template", locals: { template: @template } %>
    <% end %>
<% else %>
    <%= turbo_stream.replace "form_errors", partial: "message_templates/form_errors", locals: { template: @template } %>
<% end %>

app/views/message_templates/destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(@template)) %>
<%= turbo_stream.append('message_templates', partial: 'message_templates/no_records') if MessageTemplate.count.zero? %>

app/views/message_templates/edit.html.erb
<%= turbo_frame_tag dom_id(@template) do %>
    <%= render 'form', template: @template %>
<% end %>

app/views/message_templates/index.html.erb
<h1>Templates</h1>
<%= link_to 'New Template', new_message_template_path, data: { turbo_frame: '_top' } %>

app/views/message_templates/new.html.erb
<%= turbo_frame_tag "create-template" do %>
  <h1 class="text-3xl font-bold mb-4"><%= action_name.capitalize %> Template</h1>
  <div class="bg-white p-6 rounded-lg shadow-md">
    <%= render partial: "form", locals: { template: @template } %>
  </div>
<% end %>

app/views/message_templates/show.html.erb
<h1><%= @template.title %></h1>
<p><%= @template.content %></p>
<%= link_to 'Edit', edit_template_path(@template), data: { turbo_frame: '_top' } %>
<%= link_to 'Back', templates_path, data: { turbo_frame: '_top' } %>

app/views/message_templates/update.turbo_stream.erb
<%= turbo_stream.replace(@template, partial: "message_templates/template", locals: { template: @template }) %>