config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  devise_for :organizations
  resources :users
  resources :messages
  resources :message_templates
  resources :sms_templates
  resources :short_codes
end

app/models/sms_template.rb
class SmsTemplate < ApplicationRecord
    validates :name, presence: true
    validates :content, presence: true

    def render_template(user)
        rendered_content = content.dup
        rendered_title = name.dup
        ShortCode.all.each do |short_code|
          value = eval("#{short_code.expression}")
          rendered_content.gsub!(short_code.name, value.to_s)
          rendered_title.gsub!(short_code.name, value.to_s)
        end
        [ rendered_content, rendered_title ]
    end
end

app/controllers/sms_templates_controller.rb
class SmsTemplatesController < ApplicationController
  before_action :check_organization_login  
  before_action :set_sms_template, only: %i[show edit update destroy]
  
    def index
      @sms_templates = SmsTemplate.all
    end
  
    def show
        @sample_user = User.first
    end
  
    def new
      @sms_template = SmsTemplate.new
      @short_codes = ShortCode.all
    end
  
    def edit
        @short_codes = ShortCode.all
    end
  
    def create
      @sms_template = SmsTemplate.new(sms_template_params)
  
      if @sms_template.save
        redirect_to @sms_template, notice: 'Sms template was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      if @sms_template.update(sms_template_params)
        redirect_to @sms_template, notice: 'Sms template was successfully updated.'
      else 
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @sms_template.destroy
      redirect_to sms_templates_url, notice: 'Sms template was successfully destroyed.'
    end
  
    private
  
    def set_sms_template
      @sms_template = SmsTemplate.find(params[:id])
    end
  
    def sms_template_params
      params.require(:sms_template).permit(:name, :content)
    end
  end
  

app/helpers/sms_templates_helper.rb
module SmsTemplatesHelper
end

app/views/sms_templates/_form.html.erb
<%= form_with(model: @sms_template, local: true) do |form| %>
  <div class="bg-white shadow-md rounded p-6">
    <% if @sms_template.errors.any? %>
      <p class="text-red-500 text-xl italic mt-2"><%= @sms_template.errors.full_messages.first || "Something Went Wrong!" %></p>
    <% end %>
    <div class="mb-4">
      <%= form.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="mb-4">
      <%= form.label :content, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= form.text_area :content, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="flex items-center justify-between">
      <%= form.submit class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
      <%= link_to 'Back', sms_templates_path, class: 'bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
  </div>
<% end %>
<%= render 'short_codes' %>

app/views/sms_templates/_short_codes.html.erb
<%# app/views/sms_templates/_short_codes.html.erb %>
<div class="bg-white shadow-md rounded p-6 mt-6" data-controller="copy">
  <h2 class="text-xl font-bold mb-4">Available Short Codes <%= controller.controller_name %></h2>
  <table class="min-w-full bg-white">
    <thead>
      <tr>
        <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Name</th>
        <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Expression</th>
        <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @short_codes.each do |short_code| %>
        <tr class="border-b">
          <td class="py-2 px-6"><%= short_code.name %></td>
          <td class="py-2 px-6"><%= short_code.expression %></td>
          <td class="py-2 px-6">
            <button data-name="<%= short_code.name %>" data-action="click->copy#copy" class="copy-button bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded">Copy</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Add Short Code Button -->
<div class="mt-4">
  <%= link_to 'Add New Short Code', new_short_code_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
</div>

app/views/sms_templates/edit.html.erb
<%# app/views/sms_templates/new.html.erb %>
<%# app/views/sms_templates/edit.html.erb %>
<div class="container mx-auto py-6">
    <h1 class="text-2xl font-bold mb-6"><%= action_name.capitalize %> SMS Template</h1>
  
    <%= render 'form' %>
  </div>
  

app/views/sms_templates/index.html.erb
<%# app/views/sms_templates/index.html.erb %>
<div class="container mx-auto py-6">
    <h1 class="text-2xl font-bold mb-6">SMS Templates</h1>
  
    <div class="mb-4">
      <%= link_to 'New SMS Template', new_sms_template_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
  
    <div class="bg-white shadow-md rounded my-6">
      <table class="min-w-full bg-white">
        <thead>
          <tr>
            <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Name</th>
            <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Content</th>
            <th class="py-2 px-6 bg-gray-200 text-gray-600 font-bold uppercase text-sm text-left">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% if @sms_templates.any? %>
            <% @sms_templates.each do |sms_template| %>
              <tr class="border-b">
                <td class="py-2 px-6"><%= sms_template.name %></td>
                <td class="py-2 px-6"><%= sms_template.content %></td>
                <td class="py-2 px-6">
                  <%= link_to sms_template, class: 'text-blue-500 hover:text-blue-700' do %>
                  <i class="fas fa-eye"></i>
                <% end %>
                <%= link_to edit_sms_template_path(sms_template), class: 'text-blue-500 hover:text-blue-700 ml-2' do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to sms_template, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'text-red-500 hover:text-red-700 ml-2' do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>                
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="3" class="py-4 px-6 text-center text-gray-600">No results found</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/sms_templates/new.html.erb
<%# app/views/sms_templates/new.html.erb %>
<%# app/views/sms_templates/edit.html.erb %>
<div class="container mx-auto py-6">
    <h1 class="text-2xl font-bold mb-6"><%= action_name.capitalize %> SMS Template</h1>
  
   <%= render 'form'%>
  </div>
  

app/views/sms_templates/show.html.erb
<%# app/views/sms_templates/show.html.erb %>
<div class="container mx-auto py-6">
  <h1 class="text-2xl font-bold mb-6">SMS Template Details</h1>

  <div class="bg-white shadow-md rounded p-6">
    <p><strong>Name:</strong> <%= @sms_template.name %></p>
    <p><strong>Content:</strong> <%= @sms_template.content %></p>
  </div>

  <div class="mt-6">
    <%= link_to 'Edit', edit_sms_template_path(@sms_template), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <%= link_to 'Back', sms_templates_path, class: 'bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
  </div>

  <div class="bg-white shadow-md rounded p-6 mt-6">
    <h2 class="text-xl font-bold mb-4">Sample Preview For Template Name</h2>
    <p><%= @sms_template.render_template(@sample_user).second %></p>
  </div>
  <div class="bg-white shadow-md rounded p-6 mt-6">
    <h2 class="text-xl font-bold mb-4">Sample Preview For Template Content </h2>
    <p><%= @sms_template.render_template(@sample_user).first %></p>
  </div>
</div>