config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  devise_for :organizations
  resources :users
  resources :messages
  resources :message_templates
  resources :sms_templates
  resources :short_codes
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Yumdoot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body class="flex flex-col min-h-screen bg-[#1AB277]">
    <%= render partial: 'partials/header' %>
    <div class="flex flex-grow">
        <!-- Side Navigation -->
      <% if organization_signed_in? %>
        <nav class="w-64 bg-[#0F8452] text-white p-4">
            <ul>
                <li class="mb-4">
                    <%= link_to users_path, class: "flex items-center p-2 hover:bg-[#1AB277] rounded #{active_class('users')}" do %>
                        <i class="fas fa-users mr-2"></i>
                        Manage User
                    <% end %>
                </li>
                <li class="mb-4">
                    <%= link_to sms_templates_path, class: "flex items-center p-2 hover:bg-[#1AB277] rounded #{active_class('sms_templates')}" do %>
                        <i class="fas fa-envelope mr-2"></i>
                        Manage SMS Template
                    <% end %>
                </li>
                <li class="mb-4">
                    <%= link_to short_codes_path, class: "flex items-center p-2 hover:bg-[#1AB277] rounded #{active_class('short_codes')}" do %>
                        <i class="fas fa-code mr-2"></i>
                        Manage Short Code
                    <% end %>
                </li>
                <li class="mb-4">
                  <%= link_to destroy_organization_session_path, method: :delete, data: { turbo_method: :delete }, class: "flex items-center p-2 hover:bg-[#1AB277] rounded" do %>
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    Logout
                  <% end %>
                </li>
            </ul>
        </nav>
      <% end %>

        
        <!-- Main Content -->
        <main class="flex-grow container mx-auto px-4 py-8 bg-[#1AB277]">
            <% if notice.present? %>
            <div data-controller="alert" data-alert-target="alert" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative my-2" role="alert">
                <strong class="font-bold">Success!</strong>
                <span class="block sm:inline notice"><%= notice %></span>
                <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                    <svg data-action="click->alert#close" class="fill-current h-6 w-6 text-green-500 cursor-pointer" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <title>Close</title>
                        <path d="M14.348 5.652a1 1 0 10-1.414-1.414L10 7.586 7.066 4.652A1 1 0 105.652 6.066L8.586 9l-2.934 2.934a1 1 0 101.414 1.414L10 10.414l2.934 2.934a1 1 0 001.414-1.414L11.414 9l2.934-2.934z"/>
                    </svg>
                </span>
            </div>
            <% end %>
            <% if alert.present? %>
            <div data-controller="alert" data-alert-target="alert" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative my-2" role="alert">
                <strong class="font-bold">Error!</strong>
                <span class="block sm:inline alert"><%= alert %></span>
                <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                    <svg data-action="click->alert#close" class="fill-current h-6 w-6 text-red-500 cursor-pointer" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <title>Close</title>
                        <path d="M14.348 5.652a1 1 0 10-1.414-1.414L10 7.586 7.066 4.652A1 1 0 105.652 6.066L8.586 9l-2.934 2.934a1 1 0 101.414 1.414L10 10.414l2.934 2.934a1 1 0 001.414-1.414L11.414 9l2.934-2.934z"/>
                    </svg>
                </span>
            </div>
            <% end %>
            <%= yield %>
        </main>
    </div>
    <%= render partial: 'partials/footer' %>
</body>
</html>